CREATE DATABASE IF NOT EXISTS `myapi-stories`;
USE `myapi-stories`;
CREATE TABLE IF NOT EXISTS stories (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Info VARCHAR(50) NOT NULL,
    Project VARCHAR(64) NOT NULL,
    Evaluated TINYINT NOT NULL DEFAULT 0
);
